import MyProject.Determinantalideals.ReducedGroebner

/-!
Reproducible artifact audit for selected paper-facing declarations. The output
lists transitive logical dependencies; foundational Lean constants are not
project-specific axiom declarations.
-/

#print axioms Determinantal.KRS.krsEquiv
#print axioms Determinantal.exists_krsEquiv
#print axioms Determinantal.straightening_law_exists_filtered
#print axioms Determinantal.straightening_law
#print axioms Determinantal.exists_standardBitableau_basis_determinantalRing
#print axioms Determinantal.hilbertFunction_detRing_eq_card_monomialExp_width_le
#print axioms Determinantal.lemma6_monomial_mem_initGrPlusOne_iff_width
#print axioms Determinantal.theorem1_GrPlusOne_isGroebnerBasis_of_isAntidiagonalTermOrder
#print axioms Determinantal.GrPlusOne_isGroebnerBasis_of_isAntidiagonalTermOrder
#print axioms Determinantal.GrPlusOne_isGroebnerBasis_antiDiagonalLex
#print axioms Determinantal.support_normalizedGenericMinor
#print axioms Determinantal.leadingCoeff_normalizedGenericMinor
#print axioms Determinantal.antidiagExp_le_permExp_imp_minorIndex_eq
#print axioms Determinantal.GrPlusOne_isInterreduced_of_isAntidiagonalTermOrder
#print axioms Determinantal.normalizedGrPlusOne_isGroebnerBasis_of_isAntidiagonalTermOrder
#print axioms Determinantal.normalizedGrPlusOne_isReduced_of_isAntidiagonalTermOrder
#print axioms Determinantal.normalizedGrPlusOne_isReducedGroebnerBasis_of_isAntidiagonalTermOrder
#print axioms Determinantal.theorem1_normalizedGrPlusOne_isReducedGroebnerBasis_of_isAntidiagonalTermOrder
#print axioms Determinantal.normalizedGrPlusOne_isReduced_antiDiagonalLex
#print axioms Determinantal.normalizedGrPlusOne_isReducedGroebnerBasis_antiDiagonalLex
