/-
Copyright (c) 2026 Jiabai Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiabai Wang
-/
import MyProject.Determinantalideals.Basic
import MyProject.Determinantalideals.Finite
import Mathlib.RingTheory.Ideal.BigOperators

/-!
# Determinantal ideals

Compatibility layer for determinantal ideals over the project-local
`Matrix`/`MvPolynomial` API following Mathlib conventions.
-/

namespace Determinantal

section Ideal

variable (m n t : ℕ)
variable (k : Type*) [CommRing k]

/-- The ideal generated by all `t × t` minors of the generic `m × n` matrix. -/
abbrev detIdeal : Ideal (MvPolynomial (Fin m × Fin n) k) :=
  MvPolynomial.determinantalIdeal k m n t

variable {k}

/-- Every `t × t` minor belongs to the `t`-th determinantal ideal. -/
lemma minor_mem_detIdeal {m n t : ℕ} (I : MinorIndex m n t) :
    genericMinor k I ∈ detIdeal m n t k :=
  MvPolynomial.mvPolynomialMinor_mem_determinantalIdeal k I

/--
Every larger minor belongs to the determinantal ideal generated by smaller
minors. The proof is the standard induction using Laplace expansion.
-/
lemma genericMinor_mem_detIdeal_of_le {m n s t : ℕ} (k : Type*) [CommRing k]
    (hst : s ≤ t) (I : MinorIndex m n t) :
    genericMinor k I ∈ detIdeal m n s k :=
  by
    induction hst with
    | refl =>
        exact minor_mem_detIdeal (k := k) I
    | @step t hst ih =>
        rw [genericMinor, Matrix.MinorIndex.mvPolynomialMinor,
          Matrix.MinorIndex.detSubmatrix]
        rw [Matrix.det_succ_row _ 0]
        apply Ideal.sum_mem
        intro j hj
        have hminor :
            Matrix.det
              (((Matrix.submatrix (genericMatrix m n k) I.row I.col).submatrix
                (0 : Fin (t + 1)).succAbove j.succAbove)) ∈ detIdeal m n s k := by
          simpa [genericMinor_delete_eq_det_submatrix] using
            ih (I.delete 0 j)
        exact Ideal.mul_mem_left _ _ hminor

/-- Monotonicity of determinantal ideals with respect to inclusion of the corresponding sets
of minors. -/
lemma detIdeal_mono {m n : ℕ} {t₁ t₂ : ℕ}
    (h : minorSet k m n t₁ ⊆ minorSet k m n t₂) :
    detIdeal m n t₁ k ≤ detIdeal m n t₂ k :=
  by
    rw [detIdeal, detIdeal]
    refine Ideal.span_mono ?_
    intro f hf
    rcases (MvPolynomial.mem_determinantalMinorFinset k).1 hf with ⟨I, hI⟩
    exact (MvPolynomial.mem_determinantalMinorFinset k).2
      (h ⟨I, hI⟩)

/-- The determinantal ideal generated by the `t × t` minors is contained in `J` iff every
`t × t` minor belongs to `J`. -/
lemma detIdeal_le_iff {m n t : ℕ} {J : Ideal (MvPolynomial (Fin m × Fin n) k)} :
    detIdeal m n t k ≤ J
      ↔ (minorSet k m n t ⊆ J) :=
  by
    rw [detIdeal]
    constructor
    · intro h f hf
      rcases hf with ⟨I, hI⟩
      rw [← hI]
      exact h (MvPolynomial.mvPolynomialMinor_mem_determinantalIdeal k I)
    · intro h
      exact Ideal.span_le.mpr fun f hf => by
        rcases (MvPolynomial.mem_determinantalMinorFinset k).1 hf with ⟨I, hI⟩
        rw [← hI]
        exact h ⟨I, rfl⟩

/-- The determinantal ideal is the span of the range of the `minor` map. -/
lemma detIdeal_eq_span_range {m n : ℕ} (t : ℕ) :
    detIdeal m n t k =
      Ideal.span (Set.range (fun I : MinorIndex m n t => genericMinor k I)) :=
  by
    rw [detIdeal, MvPolynomial.determinantalIdeal_eq_span_determinantalMinorFinset]
    apply congrArg Ideal.span
    ext f
    constructor
    · intro hf
      rcases (MvPolynomial.mem_determinantalMinorFinset k).1 hf with ⟨I, hI⟩
      exact ⟨I, hI⟩
    · rintro ⟨I, hI⟩
      exact (MvPolynomial.mem_determinantalMinorFinset k).2 ⟨I, hI⟩

/-- A finite set containing all `t × t` minors of the generic `m × n` matrix. -/
noncomputable abbrev minorFinset (k : Type*) [CommRing k] (m n t : ℕ) :
    Finset (MvPolynomial (Fin m × Fin n) k) :=
  MvPolynomial.determinantalMinorFinset k m n t

/-- The coercion of `minorFinset` to a set is exactly the range of `minor`. -/
lemma coe_minorFinset_eq_range (m n t : ℕ) :
    ((minorFinset k m n t : Finset (MvPolynomial (Fin m × Fin n) k)) :
      Set (MvPolynomial (Fin m × Fin n) k)) =
      Set.range (fun I : MinorIndex m n t => genericMinor k I) :=
  by
    ext f
    constructor
    · intro hf
      rcases (MvPolynomial.mem_determinantalMinorFinset k).1 hf with ⟨I, hI⟩
      exact ⟨I, hI⟩
    · rintro ⟨I, hI⟩
      exact (MvPolynomial.mem_determinantalMinorFinset k).2 ⟨I, hI⟩

/-- The determinantal ideal is the span of the finite set `minorFinset`. -/
lemma detIdeal_eq_span_minorFinset (m n t : ℕ) :
    detIdeal m n t k =
      Ideal.span (minorFinset k m n t : Set (MvPolynomial (Fin m × Fin n) k)) :=
  MvPolynomial.determinantalIdeal_eq_span_determinantalMinorFinset k m n t

/-- The determinantal ideal is finitely generated. -/
lemma detIdeal_FG (m n t : ℕ) :
    (detIdeal m n t k).FG :=
  MvPolynomial.determinantalIdeal_fg k m n t

/-- If there are no `t × t` minors, then the set of such minors is empty. -/
lemma minorSet_eq_empty_of_isEmpty {m n t : ℕ} (h : IsEmpty (MinorIndex m n t)) :
    minorSet k m n t = ∅ :=
  by
    ext f
    simp [minorSet]

/-- If there are no `t × t` minors, then the corresponding determinantal ideal is `⊥`. -/
lemma detIdeal_eq_bot_of_isEmpty {m n t : ℕ} (h : IsEmpty (MinorIndex m n t)) :
    detIdeal m n t k = ⊥ :=
  by
    have hrange :
        Set.range (fun I : MinorIndex m n t => genericMinor k I) = ∅ := by
      ext f
      simp
    rw [detIdeal_eq_span_range, hrange]
    simp

end Ideal

end Determinantal
